#!/usr/bin/env Rscript

args <- commandArgs(trailingOnly = TRUE)
out_dir <- if (length(args) >= 1L) {
  args[[1L]]
} else {
  file.path("reports", "exdqlm_multivar_keep_kalman_fixture_20260520")
}
dir.create(out_dir, recursive = TRUE, showWarnings = FALSE)

Sys.setenv(
  PKG_CXXFLAGS = "-I/data/muscat_data/jaguir26/libs/eigen -I/data/muscat_data/jaguir26/libs/boost/include -DEIGEN_DONT_VECTORIZE",
  PKG_LIBS = "-L/data/muscat_data/jaguir26/libs/lib64 -L/data/muscat_data/jaguir26/libs/boost/lib -llapack -lblas -lboost_random -lboost_system -fopenmp",
  LD_LIBRARY_PATH = "/data/muscat_data/jaguir26/libs/lib64:/data/muscat_data/jaguir26/libs/boost/lib:/lib64"
)

if (!requireNamespace("Rcpp", quietly = TRUE)) {
  stop("Rcpp is required for the Kalman fixture", call. = FALSE)
}

Rcpp::sourceCpp("DISC_kalman_synth_transfer_forecast.cpp")

sym <- function(M) 0.5 * (M + t(M))
safe_solve <- function(M) solve(sym(M))

reference_filter <- function(GG, m0, C0, ex_f, ex_q, FF, y, ex_df_mat, Ones, TT) {
  n <- length(m0)
  m <- matrix(0, n, TT)
  C <- array(0, c(n, n, TT))
  for (tt in seq_len(TT)) {
    if (tt == 1L) {
      a <- GG[, , tt] %*% m0
      P <- GG[, , tt] %*% C0 %*% t(GG[, , tt])
      R <- P + ex_df_mat * P
    } else {
      a <- GG[, , tt] %*% m[, tt - 1L]
      P <- GG[, , tt] %*% C[, , tt - 1L] %*% t(GG[, , tt])
      R <- P * ex_df_mat + P * Ones
    }
    R <- sym(R)
    f <- drop(t(FF[, , tt]) %*% a) + ex_f[, tt]
    q <- sym(t(FF[, , tt]) %*% R %*% FF[, , tt] + ex_q[, , tt])
    q_inv <- safe_solve(q)
    innov <- y[, tt] - f
    m[, tt] <- drop(a + R %*% FF[, , tt] %*% q_inv %*% innov)
    C[, , tt] <- sym(R - R %*% FF[, , tt] %*% q_inv %*% t(FF[, , tt]) %*% t(R))
  }
  list(fm = m, fC = C)
}

p <- 1L
J <- 1L
ppx <- 0L
TT <- 2L
k <- 1L
dM <- 0L

GG <- array(0, c(2, 2, TT))
GG[, , 1] <- diag(2)
GG[, , 2] <- diag(2)
m0 <- c(0, 0)
C0 <- diag(2)
ex_f <- matrix(0, 2, TT)
ex_q <- array(0, c(2, 2, TT))
ex_q[, , 1] <- diag(c(0.5, 0.7))
ex_q[, , 2] <- diag(c(0.5, 0.7))
FF <- array(0, c(2, 2, TT))
FF[, 1, ] <- c(1, 0)
FF[, 2, ] <- c(1, 1)
y <- matrix(c(1, 1.4, 0.8, 1.1), nrow = 2, ncol = TT)
ex_df_mat <- matrix(0, 2, 2)
ex_df_mat_k <- matrix(0, 2, 2)
Ones <- matrix(1, 2, 2)

GG_list <- list(diag(2))
FF_list <- list(matrix(c(1, 1), nrow = 2, ncol = 1))
FFF_forecast <- list(matrix(0, nrow = 1, ncol = 1))
QQQ_forecast <- list(array(0.6, c(1, 1, 1)))
DF.MAT <- array(0, c(2, 2, 2))
DF.MAT_k <- array(0, c(2, 2, 1))
ensembles_forecast <- list(matrix(1.2, nrow = 1, ncol = 1))
ranges <- c(1)
Ones_ens <- matrix(1, 2, 2)
num_mem <- c(1)
W_list <- list(array(diag(c(0.2, 0.2)), c(2, 2, 1)))

cpp <- DISC_update_theta_synth_cpp_W(
  GG, m0, C0,
  ex_f, ex_q,
  FF, y, ex_df_mat, ex_df_mat_k, Ones,
  p, J, ppx, TT, k, dM,
  GG_list, FF_list,
  FFF_forecast, QQQ_forecast,
  DF.MAT, DF.MAT_k,
  ensembles_forecast, ranges, Ones_ens,
  sum(num_mem), num_mem, W_list,
  1e-6
)

ref <- reference_filter(GG, m0, C0, ex_f, ex_q, FF, y, ex_df_mat, Ones, TT)

max_slice_asymmetry <- function(x, n = NULL) {
  d <- dim(x)
  if (is.null(d) && !is.null(n) && length(x) == n * n) {
    x <- matrix(x, nrow = n, ncol = n)
    d <- dim(x)
  }
  if (length(d) == 2L) {
    return(max(abs(x - t(x))))
  }
  if (length(d) == 3L) {
    return(max(vapply(seq_len(d[3]), function(i) max(abs(x[, , i] - t(x[, , i]))), numeric(1))))
  }
  stop("expected matrix or 3D array for symmetry check", call. = FALSE)
}

checks <- data.frame(
  check = c(
    "historical_filtered_mean_max_abs_diff",
    "historical_filtered_cov_max_abs_diff",
    "historical_filtered_cov_symmetry_cpp",
    "historical_smoothed_cov_symmetry_cpp",
    "forecast_filtered_cov_symmetry_cpp",
    "forecast_smoothed_cov_symmetry_cpp"
  ),
  value = c(
    max(abs(cpp$fm - ref$fm)),
    max(abs(cpp$fC - ref$fC)),
    max_slice_asymmetry(cpp$fC),
    max_slice_asymmetry(cpp$sC),
    max_slice_asymmetry(cpp$fC_ens[[1]], n = 2),
    max_slice_asymmetry(cpp$sC_ens[[1]], n = 2)
  ),
  tolerance = c(1e-10, 1e-10, 1e-12, 1e-12, 1e-12, 1e-12)
)
checks$pass <- checks$value <= checks$tolerance

write.csv(checks, file.path(out_dir, "kalman_fixture_checks.csv"), row.names = FALSE)
saveRDS(
  list(cpp = cpp, reference = ref, checks = checks),
  file.path(out_dir, "kalman_fixture_payload.rds")
)

readme <- c(
  "# exDQLM keep Kalman fixture",
  "",
  "This report is generated by `repro/audits/run_exdqlm_keep_kalman_fixture.R`.",
  "It compiles `DISC_kalman_synth_transfer_forecast.cpp` and compares the",
  "historical filtered mean/covariance against a small R reference filter.",
  "It also checks symmetry of filtered and smoothed covariance outputs.",
  "",
  "## Checks",
  "",
  paste(capture.output(print(checks)), collapse = "\n")
)
writeLines(readme, file.path(out_dir, "README.md"))

if (!all(checks$pass)) {
  stop(sprintf(
    "Kalman fixture failed; see %s",
    normalizePath(file.path(out_dir, "kalman_fixture_checks.csv"), mustWork = FALSE)
  ), call. = FALSE)
}

cat(sprintf("Kalman fixture PASS: %s\n", normalizePath(out_dir, mustWork = FALSE)))
